name: niyyah

services:
  postgresql:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql

  www-niyyah-se:
    profiles: ["apps"]
    image: www-niyyah-se
    build:
      context: .
      dockerfile: apps/www-niyyah-se/Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      ORIGIN: http://localhost:8050
      DATABASE_URL: ${POSTGRES_URL}
    ports:
      - "8050:8050"
    depends_on:
      - postgresql

volumes:
  postgresql:
